---
title: "Notebook -- Plane Data analaysis"
output: html_notebook
---

```{r setup, include=FALSE, warning=FALSE}
source("planeDataAnalysis_functions.R")
library(ggplot2)
```

Read in the No Cursor data file
```{r}
# read in the noCursorDF
rawNoCurDF <- read.csv('data/processed/noCursorsOnly.csv')
rawNoCurDF$X <- NULL
```

Get angular deviation means for every target, per participant
```{r}
## TESTING
targetRepsInBlock <- 2
noCurDF <- MeanDevsPerTarget(rawNoCurDF, targetRepsInBlock = targetRepsInBlock)
```

Separate the aligned and rotated sessions
```{r}
alignedNoCurDF <- noCurDF[noCurDF$rotated_session == FALSE, ]
rotatedNoCurDF <- noCurDF[noCurDF$rotated_session == TRUE, ]
```

Subtract baseline
```{r}
noCurDF <- SubtractBaseline(rotatedSessionDF = rotatedNoCurDF, alignedSessionDF = alignedNoCurDF)
```
Note: __noCurDF is now baseline corrected__


***

## Plots

4 plots; generalization curve in...ph vs pH vs ph vs PH 

First: ph (where both are FALSE)

```{r}
ggplot(noCurDF[noCurDF$plane_visible == FALSE & noCurDF$high_targets == FALSE, ], 
       aes(target_angle, angular_dev_h * -1)) +
  geom_boxplot(aes(group = target_angle)) + 
  labs(title = "No plane, low targets") +
  scale_y_continuous(limits = c(-45, 60))
```

pH
```{r}
ggplot(noCurDF[noCurDF$plane_visible == FALSE & noCurDF$high_targets == TRUE, ], 
       aes(target_angle, angular_dev_h * -1)) +
  geom_boxplot(aes(group = target_angle)) +
  labs(title = "No plane, high targets") +
  scale_y_continuous(limits = c(-45, 60))
```

Ph
```{r}
ggplot(noCurDF[noCurDF$plane_visible == TRUE & noCurDF$high_targets == FALSE, ], 
       aes(target_angle, angular_dev_h * -1)) +
  geom_boxplot(aes(group = target_angle)) +
  labs(title = "Visible plane, low targets") +
  scale_y_continuous(limits = c(-45, 60))
```

PH
```{r}
ggplot(noCurDF[noCurDF$plane_visible == TRUE & noCurDF$high_targets == TRUE, ], 
       aes(target_angle, angular_dev_h * -1)) +
  geom_boxplot(aes(group = target_angle)) +
  labs(title = "Visible plane, high targets") +
  scale_y_continuous(limits = c(-45, 60))
```



